defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/project

version: 2
jobs:
  Checkout Code:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: [node_modules]
      - persist_to_workspace:
          root: .
          paths: [.]
  Check for vulnerabilities:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn install
      - run: yarn validate:dependencies
  Test node-12:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn install
      - run: yarn test

workflows:
  version: 2
  Test build and deploy(master only):
    jobs:
      - Checkout Code
      - Check for vulnerabilities:
          requires:
            - Checkout Code
      - Test node-12:
          requires:
            - Checkout Code
