name: Merge master to staging

on:
  schedule:
    - cron: '45 23 * * *' # every night
  workflow_dispatch: # on button click

jobs:
  merge-staging-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge master to staging
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff master -m "Auto-merge master to staging"
          git push
