name: Create and publish a package
on:
  push:
    branches: ['SOF-304_automated-deployment']
jobs:
  run-yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install packages
        run: yarn install

      - name: Validate dependencies
        run: yarn validate:dependencies

      - name: Build
        run: yarn build      

      - name: Unit test
        run: yarn unit

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: run-npm-test 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get standard version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
        id: version

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            tv2media/${{ github.event.repository.name }}:${{ steps.version.outputs.tag }}
            tv2media/${{ github.event.repository.name }}:latest